-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'CAMPAIGN_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'CAMPAIGN_LAUNCHED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYMENT_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'KYC_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'KYC_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'PAYOUT_PROCESSED';
